### ISSUE TITLE
LRAUVState fields population status

### ISSUE THREAD

**Issue by mabelzhang** [osrf/lrauv#11]
This ticket keeps track of which fields in `LRAUVState` are populated, to eventually populate all of them. The `LRAUVState` is meant to be a mirror of `SimResultStruct` in the MBARI code base, which contains all the information MBARI’s original simulation provides to the control loop.

LRAUVState is defined in [`lrauv/lrauv_ignition_plugins/proto/lrauv_state.proto`](https://github.com/osrf/lrauv/blob/main/lrauv_ignition_plugins/proto/lrauv_state.proto).

Checked box indicates populated.
Empty box indicates needs work.
(*) indicates populated but need modification (see section below).

- [x] ignition.msgs.Header header
- [ ] int32 errorPad_
- [ ] int32 utmZone_
- [ ] int32 northernHemi_
- [x] float propOmega_
- [ ] float propThrust_
- [ ] float propTorque_
- [x] float rudderAngle_
- [x] float elevatorAngle_
- [x] float massPosition_
- [x] float buoyancyPosition_
- [x] float depth_
<br>

- [x] ignition.msgs.Vector3d rph_  // roll_, pitch_, heading_ in SimResultStruct
<br>

- [x] float speed_
- [ ] double latitudeDeg_(#90)
- [ ] double longitudeDeg_ (#90)
- [ ] float netBuoy_
<br>

- [ ] ignition.msgs.Vector3d force_  // forceX_, forceY_, forceZ_ in SimResultStruct
- [x] ignition.msgs.Vector3d pos_  // posX_, posY_, posZ_ in SimResultStruct (#48)
- [x] ignition.msgs.Vector3d posRPH_  // posRoll_, posPitch_, posHeading_ in SimResultStruct
- [x] ignition.msgs.Vector3d posDot_  // posXDot_, posYDot_, posZDot_ in SimResultStruct (#48) 
- [ ] ignition.msgs.Vector3d rateUVW_  // rateU_, rateV_, rateW_ in SimResultStruct
- [ ] ignition.msgs.Vector3d ratePQR_  // rateP_, rateQ_, rateR_ in SimResultStruct
<br>

- [x] float northCurrent_ (https://github.com/osrf/lrauv/pull/77)
- [x] float eastCurrent_ (https://github.com/osrf/lrauv/pull/77)
- [x] float vertCurrent_ (https://github.com/osrf/lrauv/pull/77)
- [ ] float magneticVariation_
- [ ] float soundSpeed_
- [x] float temperature_ (https://github.com/osrf/lrauv/pull/77)
- [x] float salinity_ (https://github.com/osrf/lrauv/pull/77)
- [ ] float density_
- [ ] repeated float values_  // Size 4 (https://github.com/osrf/lrauv/pull/77)

### Populated but need modification:

Note that the coordinate frame convention interpreted by the MBARI controller is FSK.

- [x] depth_ and rph_ are currently in the ROS coordinate frame convention - x forward, z up, y left. Need to change to the FSK convention that MBARI's controller uses - x fore, y starboard (right), z keel (down). (#48)

@braanan @arjo129

**Comment by chapulina** [comment]
#81 is documenting on the message file itself which fields are populated, their units, frames of reference, etc. I suggest we close this issue after that's merged and track future changes on the message itself.
