### ISSUE TITLE
2022 M1 meta-issue

### ISSUE THREAD

**Issue by caguero** [osrf/lrauv#150]
* [x] Science data:
  *  [x] [Nearest neighbor search](https://github.com/osrf/lrauv/pull/83)
  *  [x] [Trilinear and bary-linear interpolations](https://github.com/osrf/lrauv/pull/191)
  *  [x] [Add PointCloudPacked iterators](https://github.com/ignitionrobotics/ign-msgs/pull/210)
  *  [x] [Use upstream's PointCloudPackedIterator](https://github.com/osrf/lrauv/pull/138)
  * [x] [Point cloud visualization plugin](https://github.com/ignitionrobotics/ign-gui/pull/346)
  * [x] [Use upstream's PointCloud GUI plugin](https://github.com/osrf/lrauv/pull/139)
  * [x] [Science sensor system causes glitches in sim](https://github.com/osrf/lrauv/issues/168)
  * [x] [Time interpolation](https://github.com/osrf/lrauv/pull/210)
* [x] https://github.com/osrf/lrauv/issues/48
  * [x] https://github.com/osrf/lrauv/pull/143 
  * [x] https://github.com/osrf/lrauv/pull/154
  * [x] https://github.com/osrf/lrauv/pull/155
  * [x] https://github.com/osrf/lrauv/pull/163
* [x] [Graded buoyancy improvements](https://github.com/osrf/lrauv/issues/148):
  * [x] Integrate with surface defaults.
  * [x] [Fix graded buoyancy problems](https://github.com/ignitionrobotics/ign-gazebo/pull/1297)
  * [x] #160
  * [x] #161 
  * [x] #162 
* [x] Acoustic comms integration
  * [x] [Acoustic azimuth and elevation are ENU referenced](https://github.com/osrf/lrauv/issues/169) 
* [x] [Surface winds](https://github.com/osrf/lrauv/issues/149)
  * [x] https://github.com/ignitionrobotics/ign-gazebo/pull/1357
  * [x] https://github.com/osrf/lrauv/pull/179
  * [x] https://github.com/ignitionrobotics/ign-math/pull/388
  * [x] https://github.com/ignitionrobotics/ign-math/pull/390
  * [x] https://github.com/ignitionrobotics/ign-math/pull/393
  * [x] https://github.com/ignitionrobotics/ign-math/pull/397
  * [x] https://github.com/ignitionrobotics/ign-math/pull/398
* [x] [DEM of Portuguese Ledge](https://github.com/osrf/lrauv/issues/146)
  * [x] https://github.com/osrf/lrauv/pull/172
* [x] [AHRS sensor](https://github.com/osrf/lrauv/issues/144)
  * [x] https://github.com/osrf/lrauv/pull/158
* [ ] [DVL sensor](https://github.com/osrf/lrauv/issues/145)
* [x] [Test plan](https://github.com/osrf/lrauv/issues/151)
* [x] [Restore CI](https://github.com/osrf/lrauv/issues/189)
* [ ] Docker updates:
  * [ ] [Improvements to documentation and setups](https://github.com/osrf/lrauv/pull/101)
