### ISSUE TITLE
M2 meta-issue

### ISSUE THREAD

**Issue by caguero** [osrf/lrauv#17]
* [x] Transition the code to Ignition Fortress. pull request osrf/lrauv#28.
 * [x] Add current to Ignition
 * [x] Add a VBE actuator to Tethys. pull request osrf/lrauv#30.
 * [x] Add a mass shifter actuator to Tethys. pull request osrf/lrauv#33 and pull request osrf/lrauv#43
 * [x] Add a drop-weight actuator to Tethys. pull request osrf/lrauv#32.
 * [x] Spring cleaning. pull request osrf/lrauv#40, pull request osrf/lrauv#41, pull request osrf/lrauv#42.
 * [x] Hydrodynamics improvements:
   * [x] Add the ability to disable coriolis. pull request osrf/lrauv#58 
   * [x] Use velocity control to move the mass shifter. pull request osrf/lrauv#43
   * [x]  Use Velocity to move thruster (#53)  osrf/lrauv#58
   * [x] Moving the center of buoyancy. pull request osrf/lrauv#44
 * [ ] Code validation:
   * [x] Update state message fields. Pull request osrf/lrauv#47 and pull request osrf/lrauv#48.
   * [x] 3D plot plugin to track trajectories. Pull request osrf/lrauv#59  
   * [x] Specify and create/get MBARI missions to use for validation: Mass shifter, VBS, VBS + mass shifter (pitch at 0), yoyo.
   * [ ] Mission validation using logging, plots, comparison with MBARI sim, and/or using Ben's feedback. See osrf/lrauv#63 :
     * [x] Mass shifter
     * [ ] VBS
     * [ ] VBS + mass shifter
     * [x] yoyo
