### ISSUE TITLE
M3 meta-issue

### ISSUE THREAD

**Issue by caguero** [osrf/lrauv#19]
M3 design document is [here](https://docs.google.com/document/d/1TlFyC6-RSPasTuRrzB1LvEWd7N4H5BwWYnP7KzFgR1s/edit) (courtesy of @arjo129) .

* [ ] Infrastructure:
  * [x] Enable CI to maintain vehicle/project stability. See pull request osrf/lrauv#36 and pull request osrf/lrauv#52 
  * [x] Update/clean installation and build process. See pull request osrf/lrauv#50 
  * [ ] Consider to remove the `ign` launch file (#55).
  * [x] https://github.com/osrf/lrauv/pull/82
* [x] Update VBS units. See osrf/lrauv_public#15 .
* [ ] MBARI integration:
  * [ ]  Update LRAUV state fields (#46).
* [ ] Hydrodynamics improvements:
  * [ ] Add crossterms support. Pull request osrf/lrauv#35 
  * [ ] Fix hydrodynamics issues. See osrf/lrauv_public#7
* [x] Buoyancy improvement to distinguish between water and air. See osrf/lrauv_public#13.
  * [x] ignitionrobotics/ign-math#219
  * [x] ignitionrobotics/ign-gazebo#818
  * [x] osrf/lrauv#101 . 
* [ ] Tethys model improvements: 
  * [ ] Updated inertias, split vehicle sections, new frame of reference. Pull request osrf/lrauv#37 
  * [x] Fix rudder inertia. See osrf/lrauv_public#8.
* [x] osrf/lrauv#71
  * [x] Schedule a meeting with scientists at MBARI to discuss use cases and alternatives
  * [x] Design the format (CSV, HDF5, etc.).
  * [x] Implement the parser (via a single plugin that can communicate with the sensors via Transport, or via a library that each sensor can use, ... https://github.com/osrf/lrauv/pull/86
  * [ ] Interpolate data
  * [ ] Visualize data https://github.com/osrf/lrauv/pull/87
  * [ ] Consider the same approach to capture current.
* [x] osrf/lrauv#72
  * [x] osrf/lrauv#89
* [x] osrf/lrauv#73
  * [x] Pre-requisite: https://github.com/ignitionrobotics/ign-sensors/issues/9
  * [x] https://github.com/osrf/lrauv/pull/77
* [ ] osrf/lrauv_public#1
  * [ ] Scope the tool[s]: CLI tool that generates data based on some parameters, CLI tool that converts from an existing data set to the new format created for Ignition, GUI, etc.
  * [ ] Implement the solution[s].
* [x] osrf/lrauv#66 
   * [x] Specify and create/get MBARI missions to use for validation.
   * [x] Mission validation using logging, plots, comparison with MBARI sim, and/or using Ben's feedback.
* [ ] Quality of life improvements
   * [ ] https://github.com/ignitionrobotics/ign-gazebo/issues/949
   * [x] https://github.com/ignitionrobotics/ign-gazebo/issues/821
* [ ] osrf/lrauv_public#3
