### ISSUE TITLE
2022 M2 meta-issue

### ISSUE THREAD

**Issue by caguero** [osrf/lrauv#202]
* [x] [Battery model](https://github.com/osrf/lrauv/issues/201)
  * [x]  https://github.com/osrf/lrauv/pull/207
* [x] [DVL sensor](https://github.com/osrf/lrauv/issues/145)
   * [x] Actual DVL integration. https://github.com/osrf/lrauv/pull/213
   * [x] Create a custom rendering sensor somehow. https://github.com/gazebosim/gz-sim/pull/1475
   * [x] Tests and integration
* [x] Ign to Gz migration
  * [x]  https://github.com/osrf/lrauv/pull/214
  * [x]  https://github.com/osrf/lrauv/pull/216
  * [x]  https://github.com/osrf/lrauv/pull/220
* [x] Integrate de Portuguese Ledge tiles into empty_world.sdf
  * [x] https://github.com/osrf/lrauv/pull/217 
* [x] Test plan (terrain relative navigation test)

Move to milestone 3.
* [ ] Add Ignition sensor plugin for ESP/CANON water samplers
* [ ] Acoustic comms refactor
