### ISSUE TITLE
2022 M3 meta-issue

### ISSUE THREAD

**Issue by caguero** [osrf/lrauv#225]
* [x] [Landing page / documentation](https://github.com/osrf/lrauv/issues/224)
   * [x] [Add acoustic subsystem examples ](https://github.com/osrf/lrauv/pull/236)
   * [x] Update after https://github.com/osrf/lrauv/pull/237 goes in.
* [ ] [Environmental/science data refactor](https://github.com/osrf/lrauv/issues/226)
   * [x] [Add TimeVaryingVolumetricGrid](https://github.com/gazebosim/gz-math/pull/456) 
   * [x] [Add CSV data parsing](https://github.com/gazebosim/gz-common/pull/402)
   * [x] [Add EnvironmentalData component](https://github.com/gazebosim/gz-sim/pull/1616)
   * [ ] Refactor Hydrodynamics plugin to use EnvironmentalData
   * [ ] [Refactor ScienceSensorsSystem plugin to use EnvironmentalData](https://github.com/gazebosim/gz-sim/pull/1691)
   * [ ] [Integrate upstream plugin with lrauv app.](https://github.com/osrf/lrauv/pull/250)
   * [ ] Visuallization (maybe move to next milestone?)
* [x] DVL
  * [x] [Relocate DVL to payload section](https://github.com/osrf/lrauv/pull/230)
  * [x] [Water column velocity sensing to DVL](https://github.com/osrf/lrauv/issues/223)
     * Needs EnvironmentData component!
  * [x] Issue with multiple DVLs at the same time
* [x] [Acoustic comms refactor](https://github.com/osrf/lrauv/issues/227)
* [ ] [Use upstream plugins (hydro)](https://github.com/osrf/lrauv/issues/37)
  * [ ] Allow coriolis to be disables: gazebosim/gz-sim#1692 
* [ ] [Hydrodynamics cross terms integration](https://github.com/gazebosim/gz-sim/pull/1692)
* [x] [Thruster model refactor](https://github.com/gazebosim/gz-sim/pull/1652)
* [x] [Ign to Gz migration](https://github.com/osrf/lrauv/issues/234)
* [x] Test plan (multi-vehicle)
