### ISSUE TITLE
M4 meta-issue

### ISSUE THREAD

**Issue by caguero** [osrf/lrauv#41]
* [ ] Hydrodynamics/physics improvements:
  * [ ] Add crossterms support. Pull request osrf/lrauv_private#35 
  * [ ] Fix hydrodynamics issues. See osrf/lrauv#7 , #47 
* [ ] Tethys model improvements:
  * [ ] Automate model stability. See #89
  * [ ] Updated inertias, split vehicle sections, new frame of reference. Pull request osrf/lrauv_private#37 
* [ ] Acoustic comms integration:
  * [x] #43
* [ ] Science sensor loading (osrf/lrauv_public#22) and interpolating data
  * [ ] Search for input points for interpolation https://github.com/osrf/lrauv/pull/83
  * [ ] Interpolate data
* [ ] https://github.com/osrf/lrauv/issues/42 Mission validation using logging, plots, comparison with MBARI sim, and/or using Ben's feedback.
   * [ ] Acoustic comms integration acceptance test
   * [ ] Science sensors integration acceptance test
 -------
* [x] osrf/lrauv#32
* [ ] osrf/lrauv#22
  * [x] Infrastructure to visualize data https://github.com/osrf/lrauv_private/pull/87
  * [ ] Visualize data https://github.com/osrf/lrauv/pull/70
  * [ ] Improvements to visualizing data https://github.com/osrf/lrauv/pull/88
  * [ ] Consider the same approach to capture current.
* [ ] osrf/lrauv_public#3
* [ ] MBARI integration:
  * [ ] Update LRAUV state fields (https://github.com/osrf/lrauv/issues/11)
  * [ ] https://github.com/osrf/lrauv/pull/88
* [ ] Quality of life improvements
   * [ ] https://github.com/ignitionrobotics/ign-gazebo/issues/949
* [ ] Infrastructure:
  * [ ] Consider to remove the `ign` launch file (https://github.com/osrf/lrauv/issues/14).
